// Chuỗi hiển thị dùng chung. Chuỗi riêng của một Bộ nằm ở sets/<setKey>/copy.ts.
export const copy = {
  common: {
    cancel: 'Thôi',
    swipeDelete: 'Xoá',
  },
  tabBar: {
    label: 'Điều hướng chính',
    spin: 'Quay',
    library: 'Món ăn',
    history: 'Lịch sử',
  },
  /** Nhãn độ hiếm dùng chung mọi Bộ; luôn đi kèm số sao. */
  rarity: {
    1: { stars: '⭐', label: 'Thường' },
    2: { stars: '⭐⭐', label: 'Ngon' },
    3: { stars: '⭐⭐⭐', label: 'Đặc biệt' },
  },
  login: {
    title: 'Nồi Thần',
    subtitle: 'Cả nhà đăng nhập một lần là nồi nhớ luôn.',
    email: 'Email',
    password: 'Mật khẩu',
    submit: 'Vào bếp thôi!',
    submitting: 'Đang mở cửa bếp…',
  },
  dishImage: {
    empty: 'Thêm ảnh',
  },
  retry: 'Thử lại',
  spin: {
    setPicker: (label: string) => `Bộ: ${label}`,
    greeting: 'Nay ăn gì cả nhà?',
    firstHint: 'Mở thử đi cả nhà!',
    button: 'Mở nồi!',
    spinning: 'Nồi đang sôi…',
  },
  tray: {
    title: 'Mâm cơm',
    say: 'Nồi Thần dọn mâm!',
    close: 'Để sau',
    announce: (parts: string[]) => `Mâm cơm: ${parts.join('; ')}`,
    announcePart: (group: string, name: string, rarity: string) => `${group} ${name}, ${rarity}`,
    announceEmpty: (group: string) => `${group} hết món`,
    reroll: (name: string) => `Đổi món này: ${name}`,
    locked: (name: string) => `${name}: Đang giữ`,
    unlocked: (name: string) => `${name}: Không giữ`,
    remove: (group: string, name: string | null) => (name ? `Bỏ ô ${group}: ${name}` : `Bỏ ô ${group}`),
    rerollAll: 'Đổi cả mâm',
    add: '＋ Thêm món',
    addPick: 'Thêm món nhóm nào?',
    addCancel: 'Thôi',
    openDetail: (group: string, name: string, rarity: string) => `Xem công thức: ${group} ${name}, ${rarity}`,
    detailTitle: (name: string) => `Chi tiết món ${name}`,
    backToTray: '← Về mâm',
    commit: 'Chốt mâm!',
    committing: 'Đang chốt…',
    committed: 'Chốt rồi! Mấy món này nồi giấu vài hôm nha 😋',
  },
  library: {
    search: 'Tìm món',
    searchPlaceholder: 'Gõ tên món, không cần dấu',
    groupFilter: 'Nhóm',
    all: 'Tất cả',
    notFound: 'Không thấy món này. Thêm mới luôn?',
    noMatch: 'Chưa có món nào khớp bộ lọc này.',
    clearFilters: 'Bỏ lọc',
    loading: 'Đang mở sổ món…',
    card: (name: string, group: string, rarity: string, facets: string) =>
      [name, group, rarity, facets].filter(Boolean).join(', '),
    detailClose: 'Đóng',
  },
  image: {
    add: 'Thêm ảnh món',
    change: 'Đổi ảnh món',
    optionsLabel: 'Chọn ảnh',
    camera: 'Chụp ảnh',
    gallery: 'Chọn từ thư viện',
    remove: 'Bỏ ảnh',
    processing: 'Đang sửa ảnh…',
    error: 'Ảnh này khó chịu quá, thử tấm khác nhé',
  },
  editor: {
    addTitle: 'Thêm món',
    editTitle: 'Sửa món',
    editButton: 'Sửa',
    deleteButton: 'Xoá',
    deleteTitle: (name: string) => `Xoá món ${name}?`,
    deleteBody: 'Nồi sẽ không dọn món này nữa. Mâm cũ trong lịch sử vẫn còn.',
    deleteConfirm: 'Xoá',
    deleting: 'Đang xoá…',
    deleted: 'Đã bỏ món khỏi nồi.',
    name: 'Tên món',
    namePlaceholder: 'Ví dụ: Thịt kho trứng kiểu mẹ',
    nameMissing: 'Món này tên gì nè?',
    group: 'Nhóm',
    groupMissing: 'Chọn nhóm cho món nhé.',
    rarity: 'Độ hiếm',
    save: 'Lưu',
    saving: 'Đang lưu…',
    cancel: 'Thôi',
    saved: 'Đã lưu vào nồi!',
    discardTitle: 'Bỏ thay đổi?',
    discardBody: 'Mấy chữ vừa gõ sẽ không được lưu đâu.',
    discard: 'Bỏ',
    stay: 'Ở lại',
    addButton: 'Thêm món',
  },
  history: {
    empty: 'Chưa chốt mâm nào. Qua tab Quay mở nồi thử nhé!',
    loading: 'Đang lật sổ mâm cơm…',
    more: 'Xem thêm mâm cũ',
    loadingMore: 'Đang tải thêm…',
    openDish: (name: string) => `Xem công thức ${name}`,
    trayLabel: (when: string) => `Mâm ${when}`,
    deleteButton: (when: string) => `Xoá mâm ${when}`,
    unknownTime: 'không rõ giờ',
    deleteTitle: 'Xoá mâm này?',
    deleteBody: 'Mấy món trong mâm sẽ được quay lại ngay.',
    deleteConfirm: 'Xoá',
    deleting: 'Đang xoá…',
    deleted: 'Đã xoá mâm.',
  },
  settings: {
    title: 'Cài đặt',
    open: 'Mở cài đặt',
    loading: 'Đang tải cài đặt…',
    back: '← Về màn Quay',
    cooldownLabel: 'Số ngày tránh trùng',
    cooldownHelp: (n: number) => (n === 0 ? 'Không tránh trùng: món vừa chốt vẫn có thể ra lại.' : `Món đã chốt sẽ nghỉ ${n} ngày rồi mới ra lại.`),
    decrease: 'Bớt một ngày',
    increase: 'Thêm một ngày',
    days: (n: number) => `${n} ngày`,
    save: 'Lưu',
    saving: 'Đang lưu…',
    saved: 'Đã lưu.',
    sound: 'Âm thanh khi mở nồi',
    soundHelp: 'Chỉ trên máy này.',
  },
  screens: {
    library: 'Sổ món của nhà',
    history: 'Mâm đã chốt',
  },
} as const
