import type { Rarity } from '../../engine'
import type { SeedItem } from '../types'
import type { FoodAttrs } from './attrs'

// seedKey không bao giờ đổi giữa các phiên bản (AD-8).
// Nguyên liệu và các bước viết gọn, phân cách bằng dấu ";".
function dish(
  seedKey: string,
  groupKey: string,
  rarity: Rarity,
  season: string,
  name: string,
  ingredients: string,
  steps: string,
): SeedItem<FoodAttrs> {
  const split = (s: string) => s.split(';').map((x) => x.trim()).filter(Boolean)
  return { seedKey, groupKey, name, rarity, tags: [season], attrs: { ingredients: split(ingredients), steps: split(steps) } }
}

export const foodSeed: readonly SeedItem<FoodAttrs>[] = [
  // ——— Mặn ———
  dish('trung-chien-hanh', 'man', 1, 'quanh-nam', 'Trứng chiên hành',
    '4 quả trứng; 3 cây hành lá; nước mắm; tiêu',
    'Đập trứng, cho hành thái nhỏ, chút nước mắm và tiêu, đánh đều; Làm nóng chảo với ít dầu, đổ trứng vào; Chiên lửa vừa đến khi vàng hai mặt'),
  dish('dau-phu-sot-ca-chua', 'man', 1, 'quanh-nam', 'Đậu phụ sốt cà chua',
    '4 bìa đậu phụ; 3 quả cà chua; hành lá; nước mắm; đường',
    'Cắt đậu miếng vuông, rán vàng; Phi thơm hành, xào cà chua đến khi nhừ, nêm mắm và đường; Cho đậu vào, đun liu riu 5 phút, rắc hành lá'),
  dish('thit-rang-chay-canh', 'man', 1, 'quanh-nam', 'Thịt rang cháy cạnh',
    '400g thịt ba chỉ; hành khô; nước mắm; đường; hành lá',
    'Thái thịt miếng mỏng; Rang thịt lửa vừa cho ra mỡ và se cạnh; Thêm hành khô, mắm, chút đường, đảo đến khi cháy cạnh; Rắc hành lá'),
  dish('tom-rim-man-ngot', 'man', 2, 'quanh-nam', 'Tôm rim mặn ngọt',
    '400g tôm; tỏi; nước mắm; đường; tiêu',
    'Cắt râu tôm, rửa sạch; Phi tỏi, cho tôm vào đảo đến khi đỏ; Thêm mắm, đường, rim đến khi sệt, rắc tiêu'),
  dish('thit-kho-trung', 'man', 2, 'quanh-nam', 'Thịt kho trứng',
    '500g thịt ba chỉ; 6 quả trứng vịt; nước dừa; nước mắm; đường',
    'Luộc trứng, bóc vỏ; Ướp thịt với mắm, đường 30 phút; Xào săn thịt, đổ nước dừa ngập, cho trứng vào; Kho lửa nhỏ khoảng 1 tiếng đến khi thịt mềm'),
  dish('ca-kho-to', 'man', 3, 'quanh-nam', 'Cá kho tộ',
    '500g cá basa hoặc cá lóc; nước màu; nước mắm; đường; tiêu; ớt; hành khô',
    'Ướp cá với mắm, đường, nước màu, hành khô 30 phút; Xếp cá vào tộ, thêm ít nước; Kho lửa nhỏ đến khi nước sệt, rắc tiêu và ớt'),
  dish('cha-trung-hap', 'man', 1, 'xuan', 'Chả trứng hấp',
    '4 quả trứng; 200g thịt băm; mộc nhĩ; miến; hành lá; nước mắm',
    'Ngâm mộc nhĩ, miến rồi thái nhỏ; Trộn trứng, thịt, mộc nhĩ, miến, hành, nêm mắm; Đổ ra bát, hấp 25 phút; Quết lòng đỏ lên mặt, hấp thêm 3 phút'),
  dish('ga-luoc-la-chanh', 'man', 2, 'xuan', 'Gà luộc lá chanh',
    '1 con gà ta; gừng; lá chanh; muối tiêu chanh',
    'Làm sạch gà, xát gừng; Luộc gà với gừng đến khi chín tới, ngâm thêm 10 phút; Chặt gà, rắc lá chanh thái chỉ, chấm muối tiêu chanh'),
  dish('nem-ran', 'man', 3, 'xuan', 'Nem rán',
    '300g thịt băm; bánh đa nem; miến; mộc nhĩ; nấm hương; cà rốt; trứng; hành',
    'Ngâm và thái nhỏ miến, mộc nhĩ, nấm; Trộn với thịt, cà rốt, trứng, hành, nêm vừa ăn; Cuốn chặt tay bằng bánh đa nem; Rán lửa vừa đến khi vàng giòn'),
  dish('ca-nuc-kho-ca-chua', 'man', 1, 'ha', 'Cá nục kho cà chua',
    '500g cá nục; 3 quả cà chua; hành khô; nước mắm; ớt',
    'Làm sạch cá, ướp mắm; Phi hành, xào cà chua nhừ; Xếp cá vào nồi, đổ sốt cà chua, thêm ít nước; Kho lửa nhỏ 30 phút'),
  dish('muc-xao-can-toi', 'man', 2, 'ha', 'Mực xào cần tỏi',
    '400g mực; cần tây; tỏi; hành tây; nước mắm; tiêu',
    'Làm sạch mực, khứa vảy rồng, cắt miếng; Chần mực qua nước sôi; Phi tỏi, xào hành tây và cần; Cho mực vào đảo nhanh, nêm mắm tiêu'),
  dish('bo-xao-thien-ly', 'man', 3, 'ha', 'Bò xào hoa thiên lý',
    '250g thịt bò; 300g hoa thiên lý; tỏi; dầu hào; tiêu',
    'Thái bò mỏng, ướp tỏi, dầu hào, tiêu; Xào bò lửa lớn đến khi tái, trút ra; Xào hoa thiên lý với tỏi, cho bò vào đảo đều'),
  dish('dau-nhoi-thit', 'man', 1, 'thu', 'Đậu nhồi thịt sốt cà',
    '4 bìa đậu phụ; 200g thịt băm; mộc nhĩ; 2 quả cà chua; hành lá',
    'Cắt đậu, khoét ruột, trộn ruột đậu với thịt, mộc nhĩ; Nhồi nhân vào đậu, rán sơ; Nấu sốt cà chua, cho đậu vào om 10 phút'),
  dish('suon-xao-chua-ngot', 'man', 2, 'thu', 'Sườn xào chua ngọt',
    '500g sườn non; giấm; đường; nước mắm; tỏi; tương cà',
    'Chặt sườn, luộc sơ rồi rán vàng; Pha sốt giấm, đường, mắm, tương cà; Phi tỏi, cho sườn và sốt vào, đảo đến khi sốt sệt bám đều'),
  dish('cha-ca-thi-la', 'man', 3, 'thu', 'Chả cá thì là',
    '400g chả cá; thì là; hành lá; mắm tôm; bún',
    'Nặn chả cá thành miếng dẹt, rán vàng; Phi hành, cho chả cá vào cùng thì là, hành lá đảo nhanh; Ăn kèm bún và mắm tôm'),
  dish('thit-luoc-mam-toi', 'man', 1, 'dong', 'Thịt luộc chấm mắm tỏi',
    '500g thịt ba chỉ hoặc nạc vai; hành khô; nước mắm; tỏi; ớt; chanh',
    'Luộc thịt với hành khô đến khi chín; Ngâm nước lạnh cho thịt trắng, thái mỏng; Pha mắm tỏi ớt chanh để chấm'),
  dish('ga-rang-gung', 'man', 2, 'dong', 'Gà rang gừng',
    '500g gà; gừng; nước mắm; đường; hành khô',
    'Chặt gà miếng vừa, ướp mắm, đường; Phi hành và gừng thái sợi; Cho gà vào rang lửa vừa đến khi săn và thơm'),
  dish('thit-dong', 'man', 3, 'dong', 'Thịt đông',
    '500g chân giò; mộc nhĩ; nấm hương; hạt tiêu; nước mắm',
    'Thái chân giò, chần sơ; Ninh cùng mộc nhĩ, nấm, mắm, tiêu đến khi mềm; Múc ra bát, để nguội rồi cho vào tủ lạnh đến khi đông'),
  // ——— Rau ———
  dish('rau-muong-xao-toi', 'rau', 1, 'quanh-nam', 'Rau muống xào tỏi',
    '1 bó rau muống; tỏi; nước mắm',
    'Nhặt rau, rửa sạch, để ráo; Phi thơm tỏi; Xào rau lửa lớn thật nhanh, nêm mắm'),
  dish('su-su-xao-toi', 'rau', 1, 'quanh-nam', 'Su su xào tỏi',
    '2 quả su su; tỏi; muối',
    'Gọt su su, thái sợi; Phi tỏi, cho su su vào xào; Nêm muối, xào đến khi vừa chín'),
  dish('dua-cai-muoi', 'rau', 1, 'quanh-nam', 'Dưa cải muối',
    '1kg cải bẹ; muối; đường; nước ấm',
    'Phơi héo cải, cắt khúc; Pha nước muối đường ấm; Nén cải vào hũ, đổ nước ngập; Để 2–3 ngày đến khi dưa vàng chua'),
  dish('dau-bap-luoc', 'rau', 2, 'quanh-nam', 'Đậu bắp luộc chấm kho quẹt',
    '300g đậu bắp; tóp mỡ; nước mắm; đường; tiêu',
    'Luộc đậu bắp vừa chín; Làm kho quẹt: đun mắm, đường, tóp mỡ đến khi sệt; Chấm đậu bắp với kho quẹt'),
  dish('rau-cu-luoc-kho-quet', 'rau', 3, 'quanh-nam', 'Rau củ luộc chấm kho quẹt',
    'bắp cải; cà rốt; đậu bắp; bí xanh; su su; tóp mỡ; nước mắm; đường',
    'Luộc lần lượt từng loại rau củ; Làm kho quẹt với tóp mỡ, mắm, đường, tiêu; Bày rau ra đĩa, chấm kho quẹt'),
  dish('cai-ngot-xao', 'rau', 1, 'xuan', 'Cải ngọt xào tỏi',
    '1 bó cải ngọt; tỏi; dầu hào',
    'Cắt cải khúc vừa ăn; Phi tỏi, cho cải vào xào lửa lớn; Nêm chút dầu hào'),
  dish('ngon-su-su-xao', 'rau', 2, 'xuan', 'Ngọn su su xào tỏi',
    '1 bó ngọn su su; tỏi; nước mắm',
    'Nhặt ngọn non, tước xơ; Chần sơ; Phi tỏi, xào nhanh, nêm mắm'),
  dish('mang-tuoi-xao', 'rau', 3, 'xuan', 'Măng tươi xào thịt',
    '400g măng tươi; 150g thịt ba chỉ; tỏi; nước mắm',
    'Luộc măng vài nước cho hết đắng, thái mỏng; Xào thịt cho ra mỡ; Cho măng vào xào cùng tỏi, nêm mắm'),
  dish('rau-lang-luoc', 'rau', 1, 'ha', 'Rau lang luộc',
    '1 bó rau lang; muối; nước mắm tỏi',
    'Nhặt ngọn rau lang; Luộc nước sôi có chút muối; Chấm mắm tỏi'),
  dish('nom-du-du', 'rau', 2, 'ha', 'Nộm đu đủ',
    'đu đủ xanh; cà rốt; rau răm; lạc rang; nước mắm; chanh; đường; tỏi ớt',
    'Bào sợi đu đủ, cà rốt, ngâm nước muối rồi vắt ráo; Pha nước trộn chua ngọt; Trộn đều, rắc lạc và rau răm'),
  dish('hoa-thien-ly-xao', 'rau', 3, 'ha', 'Hoa thiên lý xào tỏi',
    '300g hoa thiên lý; tỏi; nước mắm',
    'Rửa nhẹ hoa thiên lý; Phi tỏi; Xào thật nhanh lửa lớn, nêm mắm'),
  dish('dau-cove-xao', 'rau', 1, 'thu', 'Đậu cô ve xào tỏi',
    '300g đậu cô ve; tỏi; nước mắm',
    'Tước xơ, cắt khúc; Chần sơ đậu; Phi tỏi, xào đậu, nêm mắm'),
  dish('bong-bi-xao', 'rau', 2, 'thu', 'Bông bí xào tỏi',
    '300g bông bí; tỏi; nước mắm',
    'Tước xơ cuống, bỏ nhụy; Phi tỏi; Xào nhanh lửa lớn, nêm mắm'),
  dish('nom-hoa-chuoi', 'rau', 3, 'thu', 'Nộm hoa chuối',
    '1 bắp hoa chuối; rau thơm; lạc rang; nước mắm; chanh; đường; tỏi ớt',
    'Thái mỏng hoa chuối, ngâm nước chanh cho khỏi thâm; Vắt ráo, trộn nước chua ngọt; Rắc lạc và rau thơm'),
  dish('bap-cai-luoc', 'rau', 1, 'dong', 'Bắp cải luộc chấm trứng',
    '1/2 bắp cải; 1 quả trứng; nước mắm; chanh',
    'Luộc bắp cải; Dầm trứng luộc vào nước mắm chanh; Chấm bắp cải, lấy nước luộc làm canh'),
  dish('sup-lo-xao', 'rau', 2, 'dong', 'Súp lơ xào tỏi',
    '1 cây súp lơ xanh; cà rốt; tỏi; dầu hào',
    'Cắt súp lơ bông nhỏ, chần sơ; Phi tỏi, xào súp lơ và cà rốt; Nêm dầu hào'),
  dish('dua-gop', 'rau', 3, 'dong', 'Dưa góp su hào cà rốt',
    'su hào; cà rốt; giấm; đường; muối; tỏi ớt',
    'Thái lát mỏng su hào, cà rốt, bóp muối rồi vắt ráo; Nấu nước giấm đường để nguội; Ngâm rau củ với tỏi ớt 1 ngày'),
  // ——— Canh ———
  dish('canh-rau-ngot', 'canh', 1, 'quanh-nam', 'Canh rau ngót thịt băm',
    '1 bó rau ngót; 100g thịt băm; hành khô; nước mắm',
    'Vò nát rau ngót; Phi hành, xào thịt băm, thêm nước; Nước sôi cho rau vào, nêm mắm'),
  dish('canh-ca-chua-trung', 'canh', 1, 'quanh-nam', 'Canh cà chua trứng',
    '2 quả cà chua; 2 quả trứng; hành lá; nước mắm',
    'Xào cà chua với hành, thêm nước; Nước sôi, đổ trứng đánh tan vào khuấy nhẹ; Nêm mắm, rắc hành'),
  dish('canh-chua-ca', 'canh', 2, 'quanh-nam', 'Canh chua cá',
    '400g cá; me; dứa; cà chua; dọc mùng; giá; rau om; ngò gai; nước mắm; đường',
    'Dầm me lấy nước chua; Nấu nước me với dứa, cà chua; Cho cá vào, rồi dọc mùng, giá; Nêm mắm, đường, rắc rau thơm'),
  dish('canh-rieu-cua', 'canh', 3, 'quanh-nam', 'Canh riêu cua',
    '300g cua đồng xay; cà chua; đậu phụ; rau muống hoặc mồng tơi; hành; nước mắm; mắm tôm',
    'Lọc cua lấy nước; Đun nhỏ lửa cho riêu nổi; Xào cà chua, cho vào nồi cùng đậu rán; Cho rau vào, nêm vừa ăn'),
  dish('canh-cai-cuc', 'canh', 1, 'xuan', 'Canh cải cúc thịt băm',
    '1 bó cải cúc; 100g thịt băm; hành khô; nước mắm',
    'Phi hành, xào thịt, thêm nước; Nước sôi cho cải cúc vào; Nêm mắm, tắt bếp ngay'),
  dish('canh-hen', 'canh', 2, 'xuan', 'Canh hến rau cải',
    '500g hến; rau cải; hành; nước mắm',
    'Luộc hến, lấy nước và ruột hến; Xào ruột hến với hành; Đun nước hến, cho rau cải và ruột hến, nêm mắm'),
  dish('canh-bong', 'canh', 3, 'xuan', 'Canh bóng thả',
    'bóng bì; su hào; cà rốt; nấm hương; tôm khô; nước dùng xương',
    'Ngâm bóng, luộc rồi vắt ráo, cắt miếng; Ninh nước dùng xương với tôm khô; Cho rau củ, nấm, bóng vào nấu chín; Nêm vừa ăn'),
  dish('canh-bi-dao-tom', 'canh', 1, 'ha', 'Canh bí đao nấu tôm',
    '1/2 quả bí đao; 150g tôm; hành lá; nước mắm',
    'Gọt bí, thái miếng; Xào tôm với hành, thêm nước; Cho bí vào nấu mềm, nêm mắm'),
  dish('canh-cua-rau-day', 'canh', 2, 'ha', 'Canh cua rau đay mồng tơi',
    '300g cua đồng xay; rau đay; mồng tơi; mướp; muối; nước mắm',
    'Lọc cua lấy nước, đun cho riêu nổi; Cho mướp, rau đay, mồng tơi vào; Nêm vừa ăn'),
  dish('canh-suon-chua-sau', 'canh', 3, 'ha', 'Canh sườn nấu sấu',
    '400g sườn non; 5 quả sấu; rau muống hoặc bí; hành',
    'Chần sườn, ninh mềm; Cho sấu vào nấu cho ra vị chua; Thêm rau, nêm mắm, rắc hành'),
  dish('canh-bi-do', 'canh', 1, 'thu', 'Canh bí đỏ thịt băm',
    '400g bí đỏ; 100g thịt băm; hành lá; nước mắm',
    'Gọt bí, cắt miếng; Xào thịt, thêm nước; Cho bí nấu mềm, nêm mắm, rắc hành'),
  dish('canh-khoai-so', 'canh', 2, 'thu', 'Canh khoai sọ sườn',
    '400g khoai sọ; 300g sườn; rau mùi; nước mắm',
    'Ninh sườn lấy nước; Cho khoai sọ gọt sạch vào nấu nhừ; Nêm mắm, rắc rau mùi'),
  dish('canh-kho-qua', 'canh', 3, 'thu', 'Canh khổ qua nhồi thịt',
    '3 quả khổ qua; 200g thịt băm; mộc nhĩ; hành',
    'Bỏ ruột khổ qua; Trộn thịt, mộc nhĩ, hành, nhồi vào khổ qua; Nấu lửa nhỏ đến khi mềm, nêm vừa ăn'),
  dish('canh-cai-xanh-gung', 'canh', 1, 'dong', 'Canh cải xanh nấu gừng',
    '1 bó cải xanh; gừng; tôm khô hoặc thịt băm; nước mắm',
    'Đun nước với tôm khô hoặc thịt; Cho cải và gừng đập dập vào; Nêm mắm'),
  dish('canh-suon-cu-cai', 'canh', 2, 'dong', 'Canh sườn củ cải',
    '400g sườn; 1 củ cải trắng; hành lá; nước mắm',
    'Chần sườn, ninh mềm; Cho củ cải cắt khúc vào nấu mềm; Nêm mắm, rắc hành'),
  dish('canh-ca-ro-rau-cai', 'canh', 3, 'dong', 'Canh cá rô rau cải',
    '3 con cá rô đồng; rau cải; gừng; hành',
    'Luộc cá, gỡ thịt, lọc nước; Xào thịt cá với hành; Đun nước cá, cho rau cải, gừng và thịt cá; Nêm vừa ăn'),
]
